//
//  UIFont+Additions.swift
//
//  Generated by Zeplin on 11/2/17.
//  Copyright (c) 2017 cornell.sun. All rights reserved. 
//

import UIKit

extension UIFont {

    class var settingsPageHeader: UIFont {
        return UIFont(name: "SanFranciscoDisplay-Bold", size: 36.0)!
    }

    class var articleTitle: UIFont {
        return UIFont(name: "KeplerStd-Bold", size: 23.0)!
    }

    class var articleBody: UIFont {
        return UIFont(name: "Georgia", size: 18.0)!
    }

    class var headerTitle: UIFont {
        return UIFont.systemFont(ofSize: 16, weight: .bold)
    }

    class var listText: UIFont {
        return UIFont.systemFont(ofSize: 16, weight: .medium)
    }

    class var blockQuote: UIFont {
        return UIFont(name: "Georgia-Bold", size: 18.0)!
    }

    class var listSubtext: UIFont {
        return UIFont.systemFont(ofSize: 14, weight: .regular)
    }

    class var secondaryHeader: UIFont {
        return UIFont.systemFont(ofSize: 14, weight: .semibold)
    }

    class var cellInformationText: UIFont {
        return UIFont.systemFont(ofSize: 11, weight: .medium)
    }

    class var photoCaption: UIFont {
        return UIFont(name: "Georgia", size: 14.0)!
    }

    class var photoCaptionCredit: UIFont {
        return UIFont(name: "Georgia", size: 11.0)!
    }

    class var subSecondaryHeader: UIFont {
        return UIFont.systemFont(ofSize: 11, weight: .regular)
    }

}
