# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cornell Sun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Cornell Sun
  pod 'Moya'
  pod 'Moya-ModelMapper', '5.0.0'
  pod 'IGListKit', '~> 3.1.1'
  pod 'PINRemoteImage'
  pod 'SnapKit', '~> 4.0'
  pod 'HTMLString', '~> 4.0'
  pod 'Kingfisher', '~> 4.7.0'
  pod 'ImageSlideshow', :git=> 'https://github.com/AAAstorga/ImageSlideshow.git', :commit => 'bec5f17bd71d32d289378e1ba787a55cfa80bcce'
  pod 'ImageSlideshow/Kingfisher', :git=> 'https://github.com/AAAstorga/ImageSlideshow.git', :commit => 'bec5f17bd71d32d289378e1ba787a55cfa80bcce'
  pod 'Google-Mobile-Ads-SDK'
  pod 'SwiftSoup'
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
  pod 'IQKeyboardManagerSwift'
  pod 'SkeletonView'
  pod 'UICircularProgressRing'
  pod 'Motion'
  pod 'Fabric'
  pod 'Crashlytics'

target 'SunNotificationServiceExtension' do
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

  target 'Cornell SunTests' do
      inherit! :search_paths
      pod 'Moya'
      pod 'Moya-ModelMapper', '5.0.0'

      end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        #if target.name == "ImageSlideshow-ImageSlideshow"
        target.build_configurations.each do |config|
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
            #end
    end
end
