# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cornell Sun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Cornell Sun
  pod 'Moya'
  pod 'Moya-ModelMapper', '5.0.0'
  pod 'IGListKit', '~> 3.1.1'
  pod 'PINRemoteImage'
  pod 'LGSideMenuController'
  pod 'SnapKit', '~> 4.0'
  pod 'HTMLString', '~> 4.0'
  pod 'Kingfisher', '~> 4.0'

  target 'Cornell SunTests' do
      inherit! :search_paths
      pod 'Moya'
      pod 'Moya-ModelMapper', '5.0.0'

      end

end
