//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 11/2/17.
//  Copyright (c) 2017 cornell.sun. All rights reserved.
//

import UIKit

extension UIColor {

    @nonobjc class var brick: UIColor {
        return UIColor(red: 179.0 / 255.0, green: 27.0 / 255.0, blue: 27.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var grayMid: UIColor {
        return UIColor(red: 248/255, green: 248/255, blue: 248/255, alpha: 1)
    }

    @nonobjc class var subscribeTextField: UIColor {
        return UIColor(red: 217/256, green: 217/256, blue: 217/256, alpha: 1)
    }

    @nonobjc class var black5: UIColor {
        return UIColor(red: 0.97, green: 0.97, blue: 0.97, alpha: 1.0)
    }

    @nonobjc class var black20: UIColor {
        return UIColor(white: 0.0, alpha: 0.2)
    }

    @nonobjc class var black70: UIColor {
        return UIColor(white: 0.0, alpha: 0.7)
    }

    @nonobjc class var collectionBackground: UIColor {
        return UIColor(red: 241/255, green: 241/255, blue: 241/255, alpha: 1.0)
    }

    @nonobjc class var white: UIColor {
        return UIColor(white: 1.0, alpha: 1.0)
    }

    @nonobjc class var black40: UIColor {
        return UIColor(white: 0.0, alpha: 0.4)
    }
    
    @nonobjc class var black60: UIColor {
        return UIColor(white: 0.0, alpha: 0.6)
    }

    @nonobjc class var black90: UIColor {
        return UIColor(white: 0.0, alpha: 0.9)
    }

    @nonobjc class var lightGray2: UIColor {
        return UIColor(white: 240.0/255.0, alpha: 1.0)
    }
    
    // New Color Scheme
    
    @nonobjc class var lightText: UIColor {
        return UIColor(red: 41/255, green: 41/255, blue: 41/255, alpha: 1.0)
    }
    
    @nonobjc class var darkCell: UIColor {
        return UIColor(red: 30/255, green: 27/255, blue: 32/255, alpha: 1.0)
    }
    
    @nonobjc class var darkText: UIColor {
        return UIColor(red: 255/255, green: 255/255, blue: 255/255, alpha: 0.9)
    }
    
    @nonobjc class var darkTint: UIColor {
        return UIColor(red: 36.0 / 255.0, green: 36.0 / 255.0, blue: 46.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var unselectedDark: UIColor {
        return UIColor(red: 216/255, green: 216/255, blue: 216/255, alpha: 0.8)
    }
    
    @nonobjc class var white5: UIColor {
        return UIColor(white: 1.0, alpha: 0.05)
    }
    
    @nonobjc class var white90: UIColor {
        return UIColor(white: 1.0, alpha: 0.9)
    }
    
    @nonobjc class var white40: UIColor {
        return UIColor(white: 1.0, alpha: 0.4)
    }
    
    @nonobjc class var white60: UIColor {
        return UIColor(white: 1.0, alpha: 0.6)
    }
    
    @nonobjc class var darkTableHeader: UIColor {
        return UIColor(red: 42/255, green: 42/255, blue: 55/255, alpha: 1.0)
    }

    @nonobjc class var dividerGray: UIColor {
        UIColor(red: 0.941, green: 0.941, blue: 0.941, alpha: 1)
    }

    @nonobjc class var authorGray: UIColor {
        UIColor(red: 0.463, green: 0.447, blue: 0.447, alpha: 1)
    }

    @nonobjc class var authorSelectGray: UIColor {
        UIColor(red: 0.571, green: 0.571, blue: 0.571, alpha: 1)
    }


    // New Onboarding Colors
    @nonobjc class var onboardingGradientTop: UIColor {
        return UIColor(red: 198.0/255.0, green: 94.0/255.0, blue: 94.0/255.0, alpha: 1.0)
    }

    @nonobjc class var onboardingGradientBottom: UIColor {
        return UIColor(red: 108.0/255.0, green: 14.0/255.0, blue: 14.0/255.0, alpha: 1.0)
    }

    @nonobjc class var onboardingPageControllerDeselected: UIColor {
        return UIColor(red: 196.0/255.0, green: 196.0/255.0, blue: 196.0/255.0, alpha: 1.0)
    }

    @nonobjc class var onboardingTableViewLabel: UIColor {
        return UIColor(red: 242.0/255.0, green: 242.0/255.0, blue: 242.0/255.0, alpha: 1.0)
    }

}
