//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 11/2/17.
//  Copyright (c) 2017 cornell.sun. All rights reserved.
//

import UIKit

extension UIColor {

    @nonobjc class var brick: UIColor {
        return UIColor(red: 179.0 / 255.0, green: 27.0 / 255.0, blue: 27.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var grayMid: UIColor {
        return UIColor(red: 248/255, green: 248/255, blue: 248/255, alpha: 1)
    }

    @nonobjc class var subscribeTextField: UIColor {
        return UIColor(red: 217/256, green: 217/256, blue: 217/256, alpha: 1)
    }

    @nonobjc class var black5: UIColor {
        return UIColor(red:0.97, green:0.97, blue:0.97, alpha:1.0)
    }

    @nonobjc class var black20: UIColor {
        return UIColor(white: 0.0, alpha: 0.2)
    }

    @nonobjc class var black70: UIColor {
        return UIColor(white: 0.0, alpha: 0.7)
    }

    @nonobjc class var collectionBackground: UIColor {
        return UIColor(red: 241/255, green: 241/255, blue: 241/255, alpha: 1.0)
    }

    @nonobjc class var white: UIColor {
        return UIColor(white: 1.0, alpha: 1.0)
    }

    @nonobjc class var black40: UIColor {
        return UIColor(white: 0.0, alpha: 0.4)
    }
    
    @nonobjc class var black60: UIColor {
        return UIColor(white: 0.0, alpha: 0.6)
    }

    @nonobjc class var black90: UIColor {
        return UIColor(white: 0.0, alpha: 0.9)
    }

    @nonobjc class var lightGray2: UIColor {
        return UIColor(white: 240.0/255.0, alpha: 1.0)
    }

}
