//
//  UIColor+Additions.swift
//
//  Generated by Zeplin on 11/2/17.
//  Copyright (c) 2017 cornell.sun. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var whiteTwo: UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var warmGrey: UIColor {
		return UIColor(white: 151.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var black: UIColor {
		return UIColor(white: 41.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var blackTwo: UIColor {
		return UIColor(white: 3.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var blackThree: UIColor {
		return UIColor(white: 0.0, alpha: 1.0)
	}
}
