//
//  UIFont+Additions.swift
//
//  Generated by Zeplin on 11/2/17.
//  Copyright (c) 2017 cornell.sun. All rights reserved. 
//

import UIKit

extension UIFont {

	@nonobjc class var articleViewTitle: UIFont {
        return UIFont.systemFont(ofSize: 28.0, weight: .bold)
	}

	@nonobjc class var articleTitle: UIFont {
        return UIFont.systemFont(ofSize: 21.0, weight: .bold)
	}

	@nonobjc class var articleBody: UIFont {
        return UIFont.systemFont(ofSize: 18.0, weight: .medium)
	}
    
    @nonobjc class var articleBodyLarge: UIFont {
        return UIFont.systemFont(ofSize: 22.0, weight: .medium)
    }
    
    @nonobjc class var articleBodySmall: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .medium)
    }

	@nonobjc class var sectionList: UIFont {
        return UIFont.systemFont(ofSize: 17.0, weight: .bold)
	}

	@nonobjc class var articleViewTheme: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .bold)
	}

	@nonobjc class var articleTheme: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .medium)
	}

	@nonobjc class var likesAndComments: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .medium)
	}

	@nonobjc class var author: UIFont {
        return UIFont.systemFont(ofSize: 13.0, weight: .medium)
	}

	@nonobjc class var caption: UIFont {
        return UIFont.systemFont(ofSize: 13.0, weight: .medium)
	}
}
