//
//  UIFont+Additions.swift
//
//  Generated by Zeplin on 11/2/17.
//  Copyright (c) 2017 cornell.sun. All rights reserved. 
//

import UIKit

extension UIFont {

	@nonobjc class var articleViewTitle: UIFont {
        return UIFont(name: "KeplerStd-Bold", size: 22)!
	}

    @nonobjc class var bookmarkTitle: UIFont {
        return UIFont(name: "KeplerStd-Bold", size: 19)!
    }

	@nonobjc class var articleTitle: UIFont {
        return UIFont(name: "KeplerStd-Bold", size: 25)!
	}

	@nonobjc class var articleBody: UIFont {
        return UIFont(name: "Georgia", size: 18)!
	}

    @nonobjc class var articleBodyLarge: UIFont {
        return UIFont(name: "Georgia", size: 22)!
    }

    @nonobjc class var articleBodySmall: UIFont {
        return UIFont(name: "Georgia", size: 14)!
    }

	@nonobjc class var sectionList: UIFont {
        return UIFont.systemFont(ofSize: 17.0, weight: .bold)
	}

	@nonobjc class var articleViewTheme: UIFont {
        return UIFont(name: "Georgia-Bold", size: 18)!
	}

	@nonobjc class var articleTheme: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .medium)
	}

	@nonobjc class var likesAndComments: UIFont {
        return UIFont.systemFont(ofSize: 14.0, weight: .medium)
	}

	@nonobjc class var author: UIFont {
        return UIFont(name: "Georgia", size: 13)!
	}

	@nonobjc class var caption: UIFont {
        return UIFont(name: "Georgia", size: 13)!
	}
}
